painel/urls.py
import json
import time

import requests
from django.http import HttpResponse, StreamingHttpResponse
from django.urls import path

from . import views


def retorno_teste(request):    
    teste = request.GET.get('q')    
    response=requests.get(f'https://servicodados.ibge.gov.br/api/v1/localidades/estados/{teste}/municipios').json()
    return HttpResponse(response)


def consulta(teste):
    for i in range(10000):
        yield '\ndata: {}\n\n'.format('message {}'.format(i+int(teste)))
        time.sleep(1)

def streamFun(request):
    teste = request.GET.get('valor')
    return StreamingHttpResponse(consulta(teste), content_type='text/event-stream')

app_name = 'painel'

urlpatterns = [
    path('', views.home, name='dashboard'),
    path('conexoes/<int:id>/', views.conexoes, name='conexoes'),
    path('clicked/', retorno_teste, name='clicado'),
    path('stream/', streamFun, name='stream')
]

projeto/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('painel/', include('painel.urls'))
]

painel/models.py
from django.db import models

# Create your models here.

painel/views.py
from django.http import HttpResponse
from django.shortcuts import render


def home(request):
    return render(request, 'painel/home.html', {
        'nome':'Igor Lemões'
    })

def conexoes(request, id):
    return render(request, 'painel/conexoes.html', {
        'numero':id
    })

painel/templates/painel/conexoes.html
{% extends 'global/base.html' %}

{% block titulo %}Conexões{% endblock titulo %}

{% block conteudo %}
{{numero}}
{% endblock conteudo %}

painel/templates/painel/home.html
{% extends 'global/base.html' %}

{% block titulo %}Dashboard{% endblock titulo %}

{% block conteudo %}
<h1>{{nome}}</h1>
Aqui um corpo para a home do painel


<div hx-sse="connect:{% url 'painel:stream' %}?valor=9 swap:message"></div>

<hr>

<button hx-get="{% url 'painel:clicado' %}"
    hx-trigger="click"
    hx-target="#parent-div"
    hx-swap="outerHTML"
>
    Click Me!
</button>

<input type="text" name="q"
    hx-get="{% url 'painel:clicado' %}"
    hx-trigger="keyup delay:500ms changed"
    hx-target="#parent-div"
    placeholder="Search..."
>

<hr>

<div id="parent-div">
    Já existo
</div>

{% endblock conteudo %}